# Generated by Django 6.1 on 2026-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_insights',
            field=models.JSONField(blank=True, help_text='AI generated insights, similar complaints, and analysis', null=True),
        ),
    ]
